string = input()
x = string.count('c=')
newstr = string.replace("c=", "@")
x += newstr.count('c-')
newstr = newstr.replace("c-", "@")
x += newstr.count('dz=')
newstr = newstr.replace("dz=", "@")
x += newstr.count('d-')
newstr = newstr.replace("d-", "@")
x += newstr.count('nj')
newstr = newstr.replace("nj", "@")
x += newstr.count('lj')
newstr = newstr.replace("lj", "@")
x += newstr.count('s=')
newstr = newstr.replace("s=", "@")
x += newstr.count('z=')
newstr = newstr.replace("z=", "@")
newstr = newstr.replace("@", "")
y = len(newstr)
print(x+y)